image: node:lts

cache:
    paths:
        - client/node_modules/
        - scraper/node_modules/

pages:
    stage: deploy
    script:
        - mkdir -p public
        - cd client
        - npm ci
        - npm run build
        - find build -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
        - mv ../public ../public-react
        - mv build ../public
    artifacts:
        paths:
            - public
    only:
        - master
